const responses = [
    "That's quite intriguing. Could you elaborate?",
    "I find that fascinating! Tell me more.",
    "Really? I'd like to hear more about that.",
    "Wow, I didn't know that! Thanks for sharing.",
    "Thanks for sharing! That's very interesting.",
    "I appreciate your insight! Fascinating.",
    "I'm intrigued. What else can you tell me?",
    "Great observation! Can you provide more details?",
    "Impressive! I'd like to learn more about it.",
    "Absolutely! I'm eager to hear more.",
    "Exactly! Your point is well-taken.",
    "I see what you mean. Can you expand on that?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Let's delve deeper into this.",
    "Awesome! Can you provide further context?",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
    "Wow, I didn't expect that! Please share more.",
    "Thanks for sharing! I'd like to learn more.",
    "I'm impressed! Can you provide more insights?",
    "Fascinating! Let's delve deeper into this topic.",
    "I'm intrigued! Can you provide examples?",
    "Great observation! Can you elaborate?",
    "Impressive insight! Please share more.",
    "Absolutely! I'd love to hear more.",
    "Exactly! Let's explore this further.",
    "Well said! Can you provide additional context?",
    "Cool! I'm eager to hear more.",
    "Awesome perspective! Let's unpack this.",
    "I appreciate your input! Please continue.",
    "That's interesting! Can you explain further?",
    "Wow, I didn't know that! Can you provide more details?",
    "Thanks for sharing! I'd like to learn more.",
    "I'm intrigued! Can you expand on that?",
    "Great insight! Can you provide examples?",
    "Impressive! I'm eager to hear more.",
    "Absolutely! Let's explore this further.",
    "Exactly! Can you provide further context?",
    "Well done! I'm impressed by your knowledge.",
    "Cool! Can you elaborate on that?",
    "Awesome! I'd like to learn more.",
    "I appreciate that perspective. Please continue.",
    "Exactly! Can you provide examples?",
    "That's quite remarkable! I'm intrigued.",
    "Brilliant observation! Please share more.",
    "Fantastic insight! I'd like to hear more.",
    "Splendid! Let's explore this further.",
    "Incredible! Can you explain in more detail?",
    "Phenomenal! I'm eager to hear your thoughts.",
    "Marvelous! Can you elaborate on that?",
    "Impressive! I'd like to understand more.",
    "Astounding! Can you provide more information?",
    "Stunning! Let's dive deeper into this topic.",
    "Magnificent! Your input is valuable.",
    "Sensational! Can you provide additional context?",
    "Extraordinary! I'd love to hear more.",
    "Wonderful insight! Let's explore further.",
    "Mind-blowing! I'm captivated by your perspective.",
    "Breathtaking! Can you provide more insights?",
    "Unbelievable! I'm keen to learn more.",
    "Mind-boggling! Please share your thoughts.",
    "Astonishing! I'm eager to hear your explanation.",
    "Inconceivable! Let's unpack this further.",
    "Remarkable! Your input is invaluable.",
    "Outstanding! Can you provide further details?",
    "Excellent point! Can you expand on it?",
    "Amazing! I'd like to hear more about this.",
    "Terrific observation! Please share more.",
    "Superb! Your insights are appreciated.",
    "Brilliant! Can you provide more context?",
    "Impressive! Let's explore this idea further.",
    "Astounding! I'm eager to hear your thoughts.",
    "Fascinating insight! Can you elaborate?",
    "I'm intrigued! Can you provide examples?",
    "Great perspective! Let's delve into this.",
    "Well said! I'd like to hear more.",
    "Cool insight! Please share your thoughts.",
    "Awesome! Can you provide further explanation?",
    "I appreciate your input! Let's explore this.",
    "Exactly! Your perspective is valuable.",
    "That's quite interesting! Can you expand on it?",
  ];
  
  export default responses;
  